# Use the .NET Core SDK as a base image for building the application
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

# Copy the project files and restore dependencies
COPY UserPermissionsApi.Infraestructure.csproj .
RUN dotnet restore

# Copy the rest of the project files and build the application
COPY . .
RUN dotnet publish -c Release -o out

# Create a smaller runtime image using the .NET Core runtime
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .

# Expose the port your application listens on
EXPOSE 80

# Define the command to run your application when the container starts
ENTRYPOINT ["dotnet", "UserPermissionsApi.Infraestructure.dll"]
